CREATE TABLE "feedback" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" uuid NOT NULL,
	"internship_duration_weeks" integer,
	"internship_location" text,
	"civic_responsibility" integer,
	"societal_awareness" integer,
	"engineering_to_society" integer,
	"social_responsibility" integer,
	"ngo_understanding" integer,
	"problem_identification" integer,
	"analytical_thinking" integer,
	"tool_application" integer,
	"incomplete_data_handling" integer,
	"collaboration_skills" integer,
	"communication_skills" integer,
	"confidence_diversity" integer,
	"time_management" integer,
	"career_influence" integer,
	"initiative_confidence" integer,
	"used_data_forms" boolean DEFAULT false,
	"used_spreadsheets" boolean DEFAULT false,
	"used_mobile_apps" boolean DEFAULT false,
	"used_programming_tools" boolean DEFAULT false,
	"programming_tools_name" text,
	"used_iot_devices" boolean DEFAULT false,
	"none_of_above" boolean DEFAULT false,
	"academic_helpfulness" text,
	"academic_help_explanation" text,
	"real_world_problem" text,
	"problem_solution" text,
	"future_engagement" text,
	"recommend_internship" text,
	"recommendation_reason" text,
	"submitted_at" text DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'Asia/Kolkata'),
	CONSTRAINT "feedback_user_id_unique" UNIQUE("user_id")
);
--> statement-breakpoint
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_user_id_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE cascade;